services:
    backend:
      build: .
      image: ghcr.io/yakruay/int221-backend:dev
      environment:
        SERVICE_VERSION: v1
        
networks:
    default:
        external:
            name: int221-network
